{"name": "test_list3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 in [0, 1, [1, 2]]", "trace": "self = <test_assertions.TestCollections object at 0x0000016DE988A0F0>\n\n    def test_list3(self):\n>       assert 2 in [0, 1, [1, 2]]\nE       assert 2 in [0, 1, [1, 2]]\n\ntests\\test_assertions.py:46: AssertionError"}, "steps": [{"name": "校验结果", "status": "passed", "attachments": [{"name": " 2 ", "source": "a402feaf-c271-4365-9f8c-ba1ef61df09f-attachment.attach"}, {"name": " [0, 1, [1, 2]]", "source": "10a1da9d-5017-4a85-9789-015302a5cb0b-attachment.attach"}], "start": 1593429174095, "stop": 1593429174095}], "start": 1593429174091, "stop": 1593429174095, "uuid": "9630b990-8017-44e4-9099-9e1efa697ef3", "historyId": "f41f6d01134d681b0f77d0ee8debd4ef", "testCaseId": "23ffd3bd274984d6f5445e18db01bc4f", "fullName": "tests.test_assertions.TestCollections#test_list3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "subSuite", "value": "TestCollections"}, {"name": "host", "value": "PC-20190912OQVB"}, {"name": "thread", "value": "5048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}