{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_marks.TestMarks object at 0x0000022CA3777E80>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        \"\"\"\n>       assert 0\nE       assert 0\n\ntests\\test_marks.py:29: AssertionError"}, "description": "\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        ", "start": 1593429990439, "stop": 1593429990439, "uuid": "f749c984-5ae8-4778-ad27-7bb1c7043905", "historyId": "a44cab49732a0aa43a757be1adf99317", "testCaseId": "bddf35a14fb9223139b80ad1c562cbae", "fullName": "tests.test_marks.TestMarks#test_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_marks"}, {"name": "subSuite", "value": "TestMarks"}, {"name": "host", "value": "PC-20190912OQVB"}, {"name": "thread", "value": "11948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_marks"}]}