{"name": "test_list3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 in [0, 1, [1, 2]]", "trace": "self = <test_assertions.TestCollections object at 0x0000022CA2E24A58>\n\n    def test_list3(self):\n>       assert 2 in [0, 1, [1, 2]]\nE       assert 2 in [0, 1, [1, 2]]\n\ntests\\test_assertions.py:46: AssertionError"}, "steps": [{"name": "校验结果", "status": "passed", "attachments": [{"name": " 2 ", "source": "1fb36c2d-acfe-4485-a498-27bb0ed70923-attachment.attach"}, {"name": " [0, 1, [1, 2]]", "source": "f1430c97-47e9-4635-a4c6-60cf08f6c53f-attachment.attach"}], "start": 1593429988484, "stop": 1593429988484}], "start": 1593429988479, "stop": 1593429988484, "uuid": "28c51b6c-0f5f-4dbc-aa4c-b7250e2724b7", "historyId": "f41f6d01134d681b0f77d0ee8debd4ef", "testCaseId": "23ffd3bd274984d6f5445e18db01bc4f", "fullName": "tests.test_assertions.TestCollections#test_list3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "subSuite", "value": "TestCollections"}, {"name": "host", "value": "PC-20190912OQVB"}, {"name": "thread", "value": "11948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}